name: "Pull & Prepare Docker Workflow"
description: "Sets name and tag, logs in to GHCR, and pulls Docker image."

runs:
  using: "composite"
  steps:
    - name: Set Name and Tag Vars
      env:
        name: "${{ env.BRANCH_NAME }}"
      run: |
        echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}
        echo "TAG=${name/\//-}" >> $GITHUB_ENV
        echo "PV=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
        echo "PLAYWRIGHT_VERSION=$(cat package.json | jq -r '.dependencies.playwright')"  >> $GITHUB_ENV

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull Image
      run: |
        docker pull $REGISTRY/$IMAGE_NAME_LC:$TAG
