name: "Checkout Calling Branch"
description: "Checks out the BackstopJS repo at the calling or current branch with shallow history."

runs:
  using: "composite"
  steps:
    - name: ⬢ Setup Node & Cache
      uses: actions/setup-node@v4
      with:
        cache: "npm"
        cache-dependency-path: package-lock.json

    - name: ↧ Install
      run: npm ci
