name: "Setup Base Workflow"
description: "Checks out the BackstopJS repo at the calling or current branch with shallow history. Pulls Docker image by branch tag. Installs dependencies. Optionally sets up interactive remote debug shell."

inputs:
  DEBUG_ENABLED:
    description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
    required: false
    default: "false"
  DEBUG_DETACHED:
    description: "whether to launch tmate in detached mode (if the tmate action is run)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup tmate session
      if: ${{ inputs.DEBUG_ENABLED }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
        detached: ${{ inputs.DEBUG_DETACHED }}

    - name: Checkout to workspace
      shell: bash
      run: |
        git clone -b ${{ github.event.pull_request.head.sha || github.head_ref || github.ref_name || github.ref }} https://github.com/${{ github.repository }}.git .
        ls -las
