name: Test Checks

on:
  workflow_dispatch:
  workflow_call:

permissions:
  actions: write
  checks: write
  contents: write
  pull-requests: write

jobs:
  sanity-test:
    name: 🤪 Sanity Test Checks
    uses: ./.github/workflows/sanity-test-checks.yml

  smoke-test:
    name: 💨 Smoke Test Checks
    uses: ./.github/workflows/smoke-test-checks.yml

  integration-test:
    name: 🧩 Integration Test Check
    uses: ./.github/workflows/integration-test-check.yml
