name: Docker Tests

on:
  workflow_dispatch:
  workflow_call:

permissions:
  checks: write
  contents: write
  pull-requests: write
  packages: write

jobs:
  sanity-test:
    name: 💨 Smoke Test Docker
    uses: ./.github/workflows/docker-smoke-test.yml

  smoke-test:
    name: 🤪 Sanity Test Docker
    uses: ./.github/workflows/docker-sanity-test.yml
